# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
gallery:
  - image:
    url: "https://docs.google.com/uc?id=1G6oTN5xdKO1g2LRrZNXtiY6apKrdbQSe"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f9HHpirzAiDhF5TioQl070rg6pZToVqd"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1u30IoBl2LAnNkUEPe4xw-dN7QkSmf-D6"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1g-lsCmskP-by55ZLJIpZQiZp7ZKq8dXn"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=13QrBh7R7zOL8YVh-VQp4zz-OO1INaMRA"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1ZQOZCnqsOfkvK-19HISsmynGKiG0NcKy"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1RTi_XcPt4EuhygQBQvgeK71sbjmy6rJm"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1X4T6bGpwFWzTadVZ-tByd832qmleuH6-"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1kmL9OA0PTHqJTfLCiRKyepowZKdTgKYN"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1Xr6hWB3jk14tI_1n-Pv4GjxsEz_xu0mG"
    size: "850x1200"
  - image:
    url: "https://drive.google.com/uc?id=1UaeBgbK7nafboi6YmC3jX5XSP0GE13Pm"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"
  - image:
    url: "https://docs.google.com/uc?id=1f5nutzpOIKu7CsUrfbBCCZReGwZAkWAI"
    size: "850x1200"

wedding_date: "August 30, 2019"
main_title: Jaime & Alexandra's
subtitle: Wedding
ceremony: Ceremony
email: jaimejazarenoiii@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/wedding" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
